server:
  port: 8083

spring:
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848    #nacos的服务地址
        cluster-name: SH             #设置nacos的集群属性
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource               #数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                #mysql驱动包
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: linjf.0529

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.linjf.cloud.entity     #所有Entity别名类所在包

logging:
  level:
    com.linjf: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

