server:
  port: 8081

spring:
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848    #nacos的服务地址
        cluster-name: SH             #设置nacos的集群属性
        group: DEFAULT_GROUP
        namespace: ac833fd0-1d74-4d67-a1e7-89b47af9c9e1   #命名空间,实现nacos的环境隔离
      config:
        server-addr: 127.0.0.1:8848
        namespace: ac833fd0-1d74-4d67-a1e7-89b47af9c9e1
  config:    #2021版之前通过bootstrap.yml文件来配置,新版本推荐使用 spring.config.import 方式引入配置
    import:
      - optional:nacos:userservice.yml?refreshEnabled=true  # 监听PROVIDER_GROUP(默认,可以通过[?group=]指定):userservice.yml
      - optional:nacos:userservice-dev.yml?refreshEnabled=true
      - nacos:userservice.yml                               # 在拉取nacos配置异常时会快速失败，会导致spring容器启动失败
      - nacos:userservice-dev.yml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource               #数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                #mysql驱动包
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: linjf.0529

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.linjf.cloud.entity     #所有Entity别名类所在包

logging:
  level:
    com.linjf: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

pattern:
  dateformat: MM-dd HH:mm:ss:SSS
  envSharedValue: 共享属性-本地
  privateValue: 私有属性-本地

